---
- name: Enable EPEL Repository on CentOS 7
  yum:
    name: epel-release
    state: latest
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: pkg - Install package
  yum:
    name: monit
    state: present
